# Generated by Django 3.1.6 on 2021-08-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_persona_correos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='correos',
            new_name='correo',
        ),
    ]
